Repository markfinal/cruiz, pull requests merged in 2025-01, with the labels that each got.

#195 Fixes #194 Update copyright to 2025
  NOTICE
  src/cruiz/resources/about_dialog.ui
Labels: enhancement

#198 Fixes #197 Migrate .flake8 config to pyproject.toml
  .flake8
  pyproject.toml
  requirements_dev.txt
Labels: enhancement

#200 Fixes #199 Migrate tox configuration to pyproject
  pyproject.toml
  requirements_dev.txt
  tox.ini
Labels: enhancement

#202 ADR: Add proposal to be lockfile centric in recipe management
  doc/adr/0002-lockfile-centric.md
Labels: enhancement

#208 Fixes #207 tox cleanup
  pyproject.toml
Labels: enhancement

#218 Fixes #217 Move tested code to cruizlib
  doc/adr/0001-Separate-non-GUI-functionality-into-library.md
  pyproject.toml
  src/cruiz/commands/context.py
  src/cruiz/interop/pod.py
  src/cruiz/manage_local_cache/managelocalcachesdialog.py
  src/cruiz/workers/api/v1/meta.py
  src/cruiz/workers/api/v2/meta.py
  src/cruizlib/__init__.py
  src/cruizlib/interop/__init__.py
  src/cruizlib/interop/pod.py
  src/cruizlib/py.typed
  tests/interop/test_pod.py
Labels: enhancement

#220 Fixes #219 Replace handrolled function to convert string to a bool
  requirements.txt
  src/cruiz/commands/context.py
  src/cruiz/interop/pod.py
  src/cruiz/recipe/recipewidget.py
  src/cruiz/workers/api/v1/meta.py
  src/cruizlib/interop/pod.py
Labels: enhancement

#222 Fixes #221 Merge the existing documentation into the code repo
  .readthedocs.yaml
  doc/developer.md
  doc/faq.md
  doc/index.md
  mkdocs.yml
  requirements_docs.txt
Labels: enhancement

#224 Fixes #223 Docs: Update to latest information
  README.md
  doc/developer.md
  doc/index.md
Labels: documentation, enhancement

#226 Fixes #225 Remove extra check=True to be passed to subprocess.run
  src/cruiz/mainwindow.py
Labels: bug

#228 Fixes #227 Remove QMessageBox static function keywords.
  src/cruiz/commands/conaninvocation.py
  src/cruiz/entrypoint.py
  src/cruiz/mainwindow.py
  src/cruiz/manage_local_cache/managelocalcachesdialog.py
  src/cruiz/manage_local_cache/widgets/installconfigdialog.py
  src/cruiz/manage_local_cache/widgets/movelocalcachedialog.py
  src/cruiz/manage_local_cache/widgets/newlocalcachewizard.py
  src/cruiz/manage_local_cache/widgets/progressdialogs.py
  src/cruiz/recipe/recipewidget.py
  src/cruiz/recipe/toolbars/buildfeatures.py
  src/cruiz/remote_browser/pages/packagebinarypage.py
  src/cruiz/remote_browser/remotebrowser.py
  src/cruiz/revealonfilesystem.py
  src/cruiz/settings/managers/cleansettings.py
  src/cruiz/settings/preferencesdialog.py
Labels: bug

#230 Fixes #229 Additional docs for required dependencies on Ubuntu 24.04
  README.md
Labels: bug, documentation

#236 Fixes #235 Add pytest coverage testing including results in PRs
  .github/workflows/main.yml
  .gitignore
  .vscode/settings.json
  pyproject.toml
  requirements_dev.txt
Labels: enhancement

#241 Fixes #240 Add test for ConanHook has_path
  tests/interop/test_pod.py
Labels: enhancement

#243 Fixes #242 Refresh .ui files for latest Qt enum naming conventions
  src/cruiz/resources/about_dialog.ui
  src/cruiz/resources/find_text_dialog.ui
  src/cruiz/resources/load_recipe_wizard.ui
  src/cruiz/resources/local_cache_add_environment.ui
  src/cruiz/resources/local_cache_add_profile_directory.ui
  src/cruiz/resources/local_cache_add_remote.ui
  src/cruiz/resources/local_cache_install_config.ui
  src/cruiz/resources/local_cache_manage.ui
  src/cruiz/resources/local_cache_move.ui
  src/cruiz/resources/local_cache_new_wizard.ui
  src/cruiz/resources/local_cache_remove_environment.ui
  src/cruiz/resources/local_cache_run_command_dialog.ui
  src/cruiz/resources/preferences.ui
  src/cruiz/resources/recipe_compiler_cache_configuration_dialog.ui
  src/cruiz/resources/recipe_local_workflow_expression_editor.ui
  src/cruiz/resources/recipe_profile_frame.ui
  src/cruiz/resources/recipe_window.ui
  src/cruiz/resources/remote_browser.ui
  src/cruiz/resources/remote_browser_fileview.ui
Labels: enhancement
